In [95]:
import numpy as np

def convert_to_matrix(file):
    '''Convert the input file to a matrix of integers.'''
    rows = file.splitlines()
    height = len(rows)
    width = len(rows[0])
    print(f"Height: {height} - Width: {width}")
    matrix = np.zeros((height, width), dtype=int)    
    for i, row in enumerate(rows):
        for j, char in enumerate(row):
            matrix[i, j] = int(char)
    print(f"Matrix:\n{matrix}")
    print(f"Matrix shape: {matrix.shape}")
    return matrix

def num_edge_elements(matrix):
    '''Count the number of edge elements in a matrix.'''
    n = matrix.shape[0]
    m = matrix.shape[1]
    return 2*n + 2*m - 4

def check_tree(matrix, i, j):
    n = matrix.shape[0]
    m = matrix.shape[1]
    tree = matrix[i, j]
    
    top_vis = True
    bottom_vis = True
    left_vis = True
    right_vis = True
    
    for k in range(0, i):
        if matrix[k, j] >= tree:
            top_vis = False
            break
    
    for k in range(i+1, n):
        if matrix[k, j] >= tree:
            bottom_vis = False
            break
        
    for k in range(0, j):
        if matrix[i, k] >= tree:
            left_vis = False
            break
        
    for k in range(j+1, m):
        if matrix[i, k] >= tree:
            right_vis = False
            break
    
    is_visible = top_vis or bottom_vis or left_vis or right_vis
    
    if is_visible:
        print(f"Tree value {matrix[i,j]} at ({i}, {j}) is visible.")
    
    return is_visible
        

def calc_visible_trees(matrix):
    '''Calculate the number of visible trees in a matrix.'''
    n = matrix.shape[0]
    m = matrix.shape[1]
    num_trees = 0
    for i in range(1, n-1):
        for j in range(1, m-1):
            if check_tree(matrix, i, j):
                num_trees += 1
    return num_trees

def part1():
    file = open("input.txt", "r").read()
    matrix = convert_to_matrix(file)
    return num_edge_elements(matrix) + calc_visible_trees(matrix)

### Part 2

def scenic(matrix, i, j):
    n = matrix.shape[0]
    m = matrix.shape[1]
    tree = matrix[i, j]
    print(f"Tree value {tree} at ({i}, {j})")
    
    # trees seen to the top
    top_trees = 0
    for k in range(i - 1, -1, -1):
        print(f"checking {matrix[k, j]}")
        if matrix[k, j] < tree:
            top_trees += 1
        elif matrix[k, j] >= tree:
            top_trees += 1
            break
    
    # trees seen to the bottom
    bottom_trees = 0
    for k in range(i + 1, n):
        if matrix[k, j] < tree:
            bottom_trees += 1
        elif matrix[k, j] >= tree:
            bottom_trees += 1
            break
        
    # trees seen to the left
    left_trees = 0
    for k in range(j - 1, -1, -1):
        if matrix[i, k] < tree:
            left_trees += 1
        elif matrix[i, k] >= tree:
            left_trees += 1
            break
    
    # trees seen to the right
    right_trees = 0
    for k in range(j + 1, m):
        if matrix[i, k] < tree:
            right_trees += 1
        elif matrix[i, k] >= tree:
            right_trees += 1
            break
        
    return top_trees * bottom_trees * left_trees * right_trees

    

def part2():
    file = open("input.txt", "r").read()
    matrix = convert_to_matrix(file)
    
    max_scenic = 0
    for i in range(1, matrix.shape[0] - 1):
        for j in range(1, matrix.shape[1] - 1):
            num = scenic(matrix, i, j)
            if num > max_scenic:
                max_scenic = num
    
    return max_scenic

part2()

Height: 99 - Width: 99
Matrix:
[[0 0 0 ... 2 1 2]
 [0 2 0 ... 2 1 0]
 [0 1 2 ... 1 2 2]
 ...
 [2 2 1 ... 1 2 1]
 [2 1 1 ... 0 2 2]
 [2 0 2 ... 2 2 1]]
Matrix shape: (99, 99)
Tree value 2 at (1, 1)
checking 0
Tree value 0 at (1, 2)
checking 0
Tree value 0 at (1, 3)
checking 1
Tree value 1 at (1, 4)
checking 1
Tree value 2 at (1, 5)
checking 0
Tree value 2 at (1, 6)
checking 2
Tree value 2 at (1, 7)
checking 1
Tree value 0 at (1, 8)
checking 1
Tree value 3 at (1, 9)
checking 3
Tree value 2 at (1, 10)
checking 1
Tree value 2 at (1, 11)
checking 0
Tree value 3 at (1, 12)
checking 1
Tree value 1 at (1, 13)
checking 2
Tree value 2 at (1, 14)
checking 0
Tree value 2 at (1, 15)
checking 3
Tree value 0 at (1, 16)
checking 0
Tree value 3 at (1, 17)
checking 1
Tree value 3 at (1, 18)
checking 1
Tree value 2 at (1, 19)
checking 2
Tree value 0 at (1, 20)
checking 1
Tree value 4 at (1, 21)
checking 3
Tree value 2 at (1, 22)
checking 1
Tree value 3 at (1, 23)
checking 2
Tree value 3 at (1, 24)
checki

172224